# airflow-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags-pvc
  namespace: airflow-elyra
spec:
  accessModes:
    - ReadWriteMany  # Important for multiple pods to access
  resources:
    requests:
      storage: 1Gi