# Airflow executor
executor: KubernetesExecutor

# Disable loading example DAGs
loadExamples: false

# DAG synchronization from Git using HTTPS
dags:
  gitSync:
    enabled: true
    repo: "https://github.com/victorfonseca/elyra-poc.git"
    branch: main

# Airflow webserver
webserver:
  service:
    type: NodePort
    ports:
      - port: 8080
        nodePort: 30880
        name: airflow-webserver

# PostgreSQL as metadata database
postgresql:
  enabled: true

# Redis (not needed for KubernetesExecutor)
redis:
  enabled: false

# Environment variables for all Airflow components
env:
  - name: AIRFLOW__CORE__LOAD_EXAMPLES
    value: "false"
  # MinIO connection
  - name: AIRFLOW_CONN_MINIO_S3
    value: "s3://minio:minio123@?endpoint_url=http%3A%2F%2Fminio.minio-system.svc.cluster.local%3A9000&region_name=us-east-1"

# Extra pip packages to install
extraPipPackages:
  - "apache-airflow-providers-amazon>=2.0.0"
  - "apache-airflow-providers-cncf-kubernetes>=2.0.0"
  - "airflow-notebook>=0.0.5"