# Airflow version
airflowVersion: "3.0.1"

# Image configuration
images:
  airflow:
    repository: apache/airflow
    tag: "3.0.1"
    pullPolicy: IfNotPresent
  gitSync:
    repository: registry.k8s.io/git-sync/git-sync
    tag: "v4.3.0"
    pullPolicy: IfNotPresent
  statsd:
    repository: quay.io/prometheus/statsd-exporter
    tag: "v0.28.0"
    pullPolicy: IfNotPresent

# Executor type
executor: "KubernetesExecutor"

# Configuration
config:
  core:
    dags_folder: /opt/airflow/dags/repo/tests/dags
    executor: KubernetesExecutor
    load_examples: "False"
  api_auth:
    jwt_secret: "eJFWR8m2hqP6tXsZ5nkvGw3BLyK9xD7CfApNVcTb4QgUEzYMjS"
  kubernetes:
    worker_container_repository: apache/airflow
    worker_container_tag: "3.0.1"
  logging:
    logging_level: INFO
  scheduler:
    log_retention_days: 15
    log_cleanup_frequency_minutes: 15
  dagprocessor:
    log_retention_days: 15
    log_cleanup_frequency_minutes: 15

# DAGs configuration
dags:
  persistence:
    enabled: true
    size: 2Gi
    accessMode: ReadWriteOnce
  gitSync:
    enabled: true
    repo: "https://github.com/victorfonseca/elyra-poc.git"
    branch: "main"
    rev: "HEAD"
    depth: 1
    maxFailures: 0
    subPath: "tests/dags"
    containerName: git-sync
    wait: 60

# Disable logs persistence
logs:
  persistence:
    enabled: false

# Disable triggerer
triggerer:
  enabled: false

# Components resources configuration
scheduler:
  resources: {}

# API Server - no specific resource requirements
apiServer:
  resources: {}

# DAG Processor configuration
dagProcessor:
  enabled: true
  resources: {}

# StatSD configuration
statsd:
  enabled: true
  resources: {}

# Database configuration using PostgreSQL
postgresql:
  enabled: true
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
  persistence:
    size: 8Gi
    accessMode: ReadWriteOnce
  image:
    repository: bitnami/postgresql
    tag: 16.1.0-debian-11-r15