dags:
  persistence:
    enabled: true
    size: 1Gi
    storageClassName: standard
  gitSync:
    enabled: true
    repo: "https://github.com/victorfonseca/elyra-poc.git"
    branch: "main"
    rev: "HEAD"
    depth: 1
    maxFailures: 0
    subPath: ""
