# airflow-rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow
  namespace: airflow-elyra
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airflow-role
  namespace: airflow-elyra
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-rolebinding
  namespace: airflow-elyra
subjects:
- kind: ServiceAccount
  name: airflow
  namespace: airflow-elyra
roleRef:
  kind: Role
  name: airflow-role
  apiGroup: rbac.authorization.k8s.io