apiVersion: v1
kind: ConfigMap
metadata:
  name: git-sync-config
  namespace: airflow-elyra
data:
  git-sync.sh: |
    #!/bin/sh
    # Initial clone
    git clone --single-branch --branch main https://github.com/victorfonseca/elyra-poc.git /tmp/repo
    mkdir -p /opt/airflow/dags
    
    # Initial sync - only if directory exists
    if [ -d "/tmp/repo/tests/dags" ]; then
      cp -r /tmp/repo/tests/dags/* /opt/airflow/dags/
      echo "Initial DAGs synchronized successfully"
    else
      echo "Warning: /tmp/repo/tests/dags directory not found during initial sync"
    fi
    
    # Continuous sync every 60 seconds
    while true; do
      echo "Syncing repository..."
      cd /tmp/repo && git pull
      
      # Clean destination directory first (preserve __pycache__)
      find /opt/airflow/dags -type f -name "*.py" -delete
      
      # Copy only if the directory exists
      if [ -d "/tmp/repo/tests/dags" ]; then
        cp -r /tmp/repo/tests/dags/* /opt/airflow/dags/
        echo "DAGs synchronized successfully"
      else
        echo "Warning: /tmp/repo/tests/dags directory not found"
      fi
      
      sleep 60
    done