hub:
  config:
    Authenticator:
      class_name: GitHubOAuthenticator
    GitHubOAuthenticator:
      client_id: client_id
      client_secret: client_secret
      oauth_callback_url: http://localhost:8080/hub/oauth_callback
      allowed_users:
        - GITHUB_USER

singleuser:
  image:
    name: ghcr.io/victorfonseca/elyra
    tag: keyward-elyra
  extraEnv:
    JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
    JUPYTER_SERVER_ROOT_DIR: "/home/jovyan"
    JUPYTER_ENABLE_LAB: "yes"
  cmd: ["jupyter-labhub"]
  defaultUrl: "/lab"
  storage:
    type: dynamic
    capacity: 20Gi
    homeMountPath: /home/jovyan
    dynamic:
      storageClass: standard
  cpu:
    limit: 2
    guarantee: 0.5
  memory:
    limit: 4G
    guarantee: 1G
  lifecycleHooks:
    postStart:
      exec:
        command: 
          - "sh"
          - "-c"
          - >
            mkdir -p /home/jovyan/work;
            mkdir -p /home/jovyan/.local/share/jupyter/metadata;
            chmod -R 775 /home/jovyan/.local
  networkPolicy:
    enabled: true
    egress:
      - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: airflow-elyra
        ports:
        - port: 8080
          protocol: TCP
      - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: minio-system
        ports:
        - port: 9000
          protocol: TCP
        - port: 9001
          protocol: TCP
      - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
        ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
      - to: []
        ports:
        - port: 8081
          protocol: TCP
      - to: []
        ports:
        - port: 8000
          protocol: TCP

proxy:
  service:
    type: NodePort