# airflow-3.0.1-simple-git.yaml
---
# Airflow version
airflowVersion: "3.0.1"

# Image configuration
images:
  airflow:
    repository: apache/airflow
    tag: "3.0.1"
    pullPolicy: IfNotPresent
  gitSync:
    repository: registry.k8s.io/git-sync/git-sync
    tag: "v4.3.0"
    pullPolicy: IfNotPresent

# Executor type
executor: "KubernetesExecutor"

# Required JWT secret for Airflow 3.0 API server
config:
  core:
    dags_folder: /opt/airflow/dags/repo/tests/dags
    executor: KubernetesExecutor
    load_examples: "False"
  api_auth:
    jwt_secret: "eJFWR8m2hqP6tXsZ5nkvGw3BLyK9xD7CfApNVcTb4QgUEzYMjS"
  kubernetes:
    worker_container_repository: apache/airflow
    worker_container_tag: "3.0.1"

# DAGs configuration
dags:
  persistence:
    enabled: true
    size: 2Gi
    accessMode: ReadWriteOnce
  gitSync:
    enabled: true
    repo: "https://github.com/victorfonseca/elyra-poc.git"
    branch: "main"
    rev: "HEAD"
    depth: 1
    maxFailures: 0
    subPath: "tests/dags"
    containerName: git-sync
    wait: 60

# Disable logs persistence
logs:
  persistence:
    enabled: false

# Disable problematic triggerer
triggerer:
  enabled: false