executor: KubernetesExecutor
dags:
  persistence:
    enabled: true
    size: 1Gi
  gitSync:
    enabled: true
    repo: "https://github.com/victorfonseca/elyra-poc.git"
    branch: "main"
    depth: 1
    maxFailures: 0
webserver:
  service:
    type: NodePort
    nodePort: 30880
