apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-dag-manager-config
  labels:
    app: airflow-dag-manager
data:
  AIRFLOW_BASE_URL: "http://airflow-webserver.airflow-elyra.svc.cluster.local:8080/api/v1"
  MINIO_ENDPOINT: "http://minio.minio-system.svc.cluster.local:9000"
  MINIO_BUCKET_NAME: "customer-bucket"
  MINIO_USE_SSL: "false"
  API_TIMEOUT: "10000"
  POLLING_INTERVAL: "30000"