apiVersion: v1
kind: Service
metadata:
  name: airflow-dag-manager-service
  labels:
    app: airflow-dag-manager
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: airflow-dag-manager

---
apiVersion: v1
kind: Service
metadata:
  name: airflow-dag-manager-nodeport
  labels:
    app: airflow-dag-manager
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: airflow-dag-manager